name: CI

env:
  MY_ENV_VAR: query_pr
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prJob:    
    
      name: Print info
      runs-on: ubuntu-latest
      
      steps:
      
      - name: setting artifact registory var
        id: artifact_reg_var
        run: |
          if [$EVENTNAME == 'push']
          then
              echo "::set-output name=artvar::shouldtriggerpullrepo"
          elif [$EVENTNAME == 'release' ]
          then
              echo "::set-output name=artvar::shouldtriggerpullrepo"
          else
              echo "::set-output name=artvar::nonoftheoperations"
          fi
        env:
          EVENTNAME: ${{ github.event_name }}
          MERGING: true

      - name: checking step variable
        run: echo ${{ steps.artifact_reg_var.outputs.artvar }}
