name: SHELL SCRIPT CONDITION BASED WORKFLOW

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    

jobs:
  shellbasedcondtioning:    
    
      name: Job 1
      runs-on: ubuntu-latest
      environment: staging
      steps:
      
      - name: setting artifact registory var
        id: artifact_reg_var
        run: |
          if [ $EVENTNAME == 'push' ] && $MERGING
          then
              echo "::set-output name=artvar::stringvalueifpush"
              echo $MERGING
              echo $EVENTNAME
          elif [ $EVENTNAME == 'release' ]
          then
              echo "::set-output name=artvar::stringvalueifrelease"
          else
              echo "::set-output name=artvar::nonoftheoperations"
          fi
        env:
          EVENTNAME: ${{ github.event_name }}
          MERGING: true
          

      - name: checking step variable
        run: echo ${{ steps.artifact_reg_var.outputs.artvar }}
