name: FIND VERSION OF ANY MODULE WORKFLOW
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  firstJob:    
    
      name: Find Module Version from Requirements.txt
      runs-on: ubuntu-latest
      
      steps:
        - name: checkout repo
          uses: actions/checkout@v2.3.4
        - name: Fetch Version of module step
          id: moduleversion
          uses: saurabhrai19/getpyversion@v1.15
          with:
            module-name: 'Flask'
            file-name: 'requirements.txt'
        - name: Get Output
          run: echo "The Module with Version- ${{ steps.moduleversion.outputs.modulewithver }}"
          
        - name: HTTP Request Action
  # You may pin to the exact commit or the version.
  # uses: fjogeleit/http-request-action@e3313c1a5f87ea3807b7034fb41abbb83a6533df
          uses: fjogeleit/http-request-action@v1.9.2
          with:
            # Request URL
            url: 'https://jsonplaceholder.typicode.com/todos?id=1' 
            method: 'GET'
          
        - name: "Call API 1"
          uses: indiesdev/curl@v1.1
          id: api
          with:
            url: https://reqres.in/api/users
            method: "POST"
            accept: 201
            body: '{ "name": "breeze", "job": "devops" }'
            log-response: true
            
        - name: "Call API 2"
          uses: indiesdev/curl@v1.1
          id: api1
          with:
            url: https://jsonplaceholder.typicode.com/posts
            method: "POST"
            accept: 201
            body: '{ "userId": 1231, "id": 54, "title": "devops", "body": "This is the body" }'
            log-response: true
          
        - name: "Call API"
          uses: indiesdev/curl@v1.1
      
          with:
            # The target URL
            # Required: true if custom-config is not set
            url: https://api.github.com/users/saurabhrai19/repos
            # The request method, basically it's one of GET|POST|PUT|PATCH
            # Default is GET
            method: "GET"
            log-response: true
            bearer-token: ${{ secrets.TOKENFORAPIRESPONSETESTING }}
        
          

            
