name: FIND VERSION OF ANY MODULE WORKFLOW

env:
  MY_ENV_VAR: query_pr
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  firstJob:    
    
      name: Find Module Version from Requirements.txt
      runs-on: ubuntu-latest
      
      steps:
        - name: checkout repo
          uses: actions/checkout@v2.3.4
        - name: Hello world action step
          id: moduleversion
          uses: saurabhrai19/getpyversion@v1.11
          with:
            module-name: 'Flask'
            file-name: 'requirements.txt'
        - name: Get Output
          run: echo "The Module with Version ${{ steps.moduleversion.outputs.modulewhver }}"
