# This is a basic workflow to help you get started with Actions

name: CI

env:
  MY_ENV_VAR: query_pr
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: GH Api 
        uses: demotcsorg/gh_graphql_action@v1.8
        with:
          GITHUB_TOKEN: ${{ secrets.GRAPHTOKEN }}
          USERNAME: saurabhrai19
          OPERATION: query_pr
  prJob:    
      name: Print info
      runs-on: ubuntu-latest
      steps:
        - name: Condition one
          if: contains(github.event_name,'push')
          uses: demotcsorg/gh_graphql_action@v1.8
          with:
            GITHUB_TOKEN: ${{ secrets.GRAPHTOKEN }}
            USERNAME: saurabhrai19
            OPERATION: query_pr
        - name: Condition two    
          if: contains(github.event_name,'pull')
          run:  |
            echo "Second condition"
            echo ${{ github.ref }}

