# This is a basic workflow to help you get started with Actions

name: Main Workflow

env:
  MY_ENV_VAR: query_pr
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prJob:    
    
      name: Print info
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        - name: Condition one
#          if: contains(github.event_name,'push') && endsWith(github.event_name, 'sh') && startsWith(github.event_name,'u')
          uses: demotcsorg/gh_graphql_action@v1.11
          with:
            GITHUB_TOKEN: ${{ secrets.GRAPHTOKEN }}
            USERNAME: demotcsorg
            OPERATION: orgmembers
        - name: Condition two    
          if: contains(github.event_name,'pullrequest')
          run:  |
            echo "Second condition"
            echo "${{ github.event.pull_request_target.merged == true }}"

