name: Workflow with conditions

env:
  envVar2: 'value' 
  envVar3: 'ss'

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches: [ main ]
    

  

jobs:
  conditionbased:
    name: Print info
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - name: Condition one
        if: ${{ env.envVar2 == 'value2' }}
        uses: allenevans/set-env@v2.0.0
        with:
          MY_ENV_VAR: 'beforeanothercondition'
      
      

      - name: Printing env var
        run: |
          echo ${{ env.MY_ENV_VAR }}
      
      - name: conditioning
        if: ${{ env.envVar3 == 'ss' }}
        uses: allenevans/set-env@v2.0.0
        with:
          MY_ENV_VAR: 'afteranothercondition'
        

      - name: Printing env var
        run: |
          echo ${{ env.MY_ENV_VAR }}

           
            
