name: Workflow with conditions

env:
  envVar2: 'value2'

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches: [ main ]
    

  

jobs:
  conditionbased:
    name: Print info
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - name: Condition one
        if: ${{ env.envVar2 == 'value2' }}
        run: |
          echo ${{ env.envVar1 }}
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          MY_ENV_VAR: 'envVar1'
        
        

      - name: Printing env var
        run: |
          echo ${{ env.MY_ENV_VAR }}

           
            
