name: Workflow with conditions

env:
  envVar2: 'value2' 
  envVar3: 's'

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches: [ main ]
    

  

jobs:
  conditionbased:
    name: Print info
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Before condition One
        run: |
          echo Condition One If Agreed will initialize the env var which will be accessible globally in other steps
      
      - name: Condition one
        if: ${{ env.envVar2 == 'value2' }}
        uses: allenevans/set-env@v2.0.0
        with:
          MY_ENV_VAR: 'condition1'
      
      

      - name: Before Second Condition
        run: |
          echo Condition Two if previous condition failed and this checking if event name pull_request and merged
      
      - name: Second Condition
        if: ${{ env.envVar3 == 'ss' }}
        uses: allenevans/set-env@v2.0.0
        with:
          MY_ENV_VAR: 'condition2'
          
      - name: Printing the action setted step env var which is globally accessible
        run: |
          echo ${{ env.MY_ENV_VAR }}
          
      - name: Step scoped env variable
        env: 
          stepscopedenv: 'stepscoped'
        run: echo ${stepscopedenv}
        
      - name: Not Accessible Step scopped Env
        run: echo ${stepscopedenv}
          
          
        

      

           
            
